spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 10
  flyway:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?sslmode=require
    user: ${DB_USER}
    password: ${DB_PASSWORD}
